### ISSUE TITLE
Jenkinsプラグインインストールに失敗する

### ISSUE THREAD

**Issue by anjunpapa** [ayapapa/alminium#133]
いつもお世話になっております。
以下の症状があり、投稿させて頂きました。

■症状
\$sudo git clone https://github.com/ayapapa/alminium.git
\$cd (展開directory)/alminium
\$sudo -E ./smelt
を実行すると、Jenkinsプラグインのインストールで、
以下のメッセージが繰り返し表示され、インストールが完了しません。

\-------------------------------------------------------------------
ERROR: Failed to install plugin reverse-proxy-auth-plugin
\### プラグインインストール中にエラーが発生しました。
\### 再度、プラグインのインストールを試みます。
Installing reverse-proxy-auth-plugin from update center
\-------------------------------------------------------------------

■環境
・OS
　Ubuntu16.04（Windows10上に構築したvagrant仮想環境のUbuntu16.04）
・プロキシ設定
　実行環境はproxyを介さないとインターネット接続不可のため、以下を設定済み。
　- bash環境変数
　- /etc/apt/apt.conf

以上です。
お手数ですがよろしくお願い致します。

**Comment by ayapapa** [comment]
@anjunpapa さん、投稿有難うございます。
調査を開始します。何かわかったら、連絡します。

**Comment by ayapapa** [comment]
@anjunpapa さん、 [issue133ブランチ](https://github.com/ayapapa/alminium/tree/issue133) に対応版をコミットしました。他のブランチで作業中のため、masterへのマージは、後日実施したいと思います。
* 原因：Jenkinsへのプロキシー設定処理がエラーとなっていました。このため、プラグインダウンロードができずにエラーになっていたものを思います。
* 対応：セキュリティ一時解除処理の前倒し、および、Jenkinsへのプロキシー設定リクエストヘッダの適正化。
一応、手元（プロキシー利用環境）では、成功するようになっています。もし、お時間が許すようでしたら、ご確認いただければ幸いです。
clone する場合は、以下のようにしてください。
`git clone -b issue133 https://github.com/ayapapa/alminium`

**Comment by anjunpapa** [comment]
@ayapapaさん、
さっそくの対応ありがとうございます。

$git clone -b issue133 https://github.com/ayapapa/alminium
を実行し、再度
$sudo ./smelt
を実行しましたが、以下のエラーとなりました。
・「/etc/default/jenkins が無い」とのメッセージが出ました。
・jenkinsサービスが再起動されないようです。
以下、該当箇所前後の写しです。

よろしくお願いいたします。

\------------------------------------------------------------------------------------------------------
gpg: no valid OpenPGP data found.
W: GPG error: http://pkg.jenkins-ci.org/debian-stable binary/ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9B7D32F2D50582E6
W: The repository 'http://pkg.jenkins-ci.org/debian-stable binary/ Release' is not signed.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  daemon
The following NEW packages will be installed:
  daemon jenkins
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 76.6 MB of archives.
After this operation, 77.6 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  jenkins
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
sed: can't read /etc/default/jenkins: No such file or directory
Failed to restart jenkins.service: Unit jenkins.service not found.
chown: invalid user: ‘jenkins:jenkins’
セキュリティ解除
waiting for ready...
waiting for ready...
waiting for ready...
waiting for ready...
waiting for ready...
waiting for ready...
waiting for ready...
waiting for ready...
....以下繰り返し。
\-------------------------------------------------------------------------------------------------------

**Comment by ayapapa** [comment]
@anjunpapa さん、
なぜか後退している現象ですね。
エラーを見ると、Jenkinsパッケージのダウンロードができていないようです。
推測としては、Jenkinsパッケージサイトがメンテ中で中途半端な状態だったってな感じです。

明日、自分のproxy環境で試してみます。（昨日は、確かにちゃんとJenkinsのダウンロードとインストールは成功していました）

**Comment by anjunpapa** [comment]
@ayapapa さん、

アドバイスをありがとうございました。
時間をおいてやり直したところ、うまくいきました！！
Jenkins本体、および、Jenkinsプラグイン共に、インストールが完了し、動作致しました。
メンテ中だったかも知れませんね。

対応頂き、お礼申し上げます。

**Comment by ayapapa** [comment]
@anjunpapa さん、
確認有難うございます。
インストールが成功して良かったです。
また、何かありましたら、投稿願います。有難うございました。
